on:
  create:
    ref_type: branch
    branches: ['release-**']
  push:
    branches: ['release-**']
  pull_request:
    branches: ['release-**']
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        $APIKEY="${{ secrets.FRENDS_NUGET_FEED_KEY }}"
        $RELEASE_BRANCH=$(git branch --show-current)
        $VER=$RELEASE_BRANCH.Replace("release-", "")
        Write-Host "Building version: $VER"
        dotnet pack --configuration Release --include-source --output . /p:Version=$VER .\Frends.HIT.RoboSharp\Frends.HIT.RoboSharp.csproj
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body_path: README.md
        files: |
          Frends.HIT.RoboSharp.*.nupkg
          README.md