on:
  push:
    paths: ['Frends.HIT.RoboSharp/**']
    branches: ['main']
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push
      run: |
        $APIKEY="${{ secrets.FRENDS_NUGET_FEED_KEY }}"
        $VER=$(Get-Content -Path .\Version).Split(".")
        if ($VER.Length -eq 2) {
          $VER = @($VER[0], $VER[1], 0)
        }
        $VER[2] = [int]$VER[2] + 1
        $VER = $VER -join "."
        Write-Host "Building version: $VER"
        dotnet pack --configuration Release --include-source --output . /p:Version=$VER .\${{ github.event.repository.name }}\${{ github.event.repository.name }}.csproj
        dotnet nuget push .\${{ github.event.repository.name }}.$VER.nupkg --source ${{ secrets.FRENDS_NUGET_FEED_URL }} --api-key "$APIKEY"
        Set-Content -PATH .\VERSION -Value $VER
        Remove-Item -Path ./${{ github.event.repository.name }}.*.nupkg
        git config user.email "autopush@hoglan.dev"
        git config user.name "AutoPush"
        git add VERSION
        git commit -m "[AUTO] Increment version number to $VER"
        git push origin main