on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NUGET_PKG_NAME: ${{ github.event.repository.name }}
      NUGET_PKG_FEED: ${{ secrets.FRENDS_NUGET_FEED_URL }}
      NUGET_PKG_KEY: ${{ secrets.FRENDS_NUGET_FEED_KEY }}
      GH_PUSH_EMAIL: autopush@developer.local
      GH_PUSH_NAME: AutoPush
    steps:
      - name: Checkout
        uses: actions/checkout@v2  

      - name: Build and push
        
        run: |
          IFS=. read -r v1 v2 v3 <<< $(cat ./VERSION)
          v3=$((v3 + 1))
          VERSION="$v1.$v2.$v3"
          echo "Building version: $VERSION"
          dotnet pack --configuration Release --include-source --output . /p:Version=$VERSION "${{ env.NUGET_PKG_NAME }}/${{ env.NUGET_PKG_NAME }}.csproj"
          dotnet nuget push "${{ env.NUGET_PKG_NAME }}.$VERSION.nupkg" --source "${{ env.NUGET_PKG_FEED }}" --api-key "${{ env.NUGET_PKG_KEY }}"
          echo "$VERSION" > VERSION
          rm -f "./${{ env.NUGET_PKG_NAME }}.*.nupkg"
          git config user.email "${{ env.GH_PUSH_EMAIL }}"
          git config user.name "${{ env.GH_PUSH_NAME }}"
          git add VERSION
          git commit -m "[AUTO] Increment version number"
          git push origin main
          echo "Done"